/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import BD.Conexion;
import static Interfaz.Inicio.pnlDerecho;
import java.awt.BorderLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauri
 */
public class PnlEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicioSesion
     */
    private DefaultTableModel dtm;
    private Object[] obj = new Object[5];
    public static boolean estado = true;
    public static ArrayList<String> idEmpleado = new ArrayList<>();
    public static Vector registro;

    public PnlEmpleados() {
        initComponents();
        dtm = new DefaultTableModel();
        dtm.addColumn("ID EMPLEADO");
        dtm.addColumn("NOMBRE");
        dtm.addColumn("CEDULA");
        dtm.addColumn("TELEFONO");
        dtm.addColumn("DIRECCION");
        tblEmpleados.setModel(dtm);
        LlenarTabla("SELECT * FROM empleado");
        llenarCmb(cmbSucursales);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void LlenarTabla(String comando) {
        try {
            PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                obj[0] = rs.getString(1);
                obj[1] = rs.getString(2);
                obj[2] = rs.getString(3);
                obj[3] = rs.getString(4);
                obj[4] = rs.getString(5);
                idEmpleado.add(rs.getString(1));
                dtm.addRow(obj);
            }
            pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void limpiarTabla() {
        System.out.println(dtm.getRowCount());
        int n = dtm.getRowCount();
        int bandera = 0;
        while (bandera < n) {
            dtm.removeRow(0);
            bandera += 1;
        }
    }

    static public void llenarCmb(JComboBox cmb) {
        try {
            cmb.removeAllItems();
            cmb.addItem("  ");
            String comando = "SELECT numerosucur FROM sucursal";
            PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String sucursalID = rs.getString(1);
                cmb.addItem(sucursalID);
            }
            pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEmpleadosTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreEmp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbSucursales = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCedulaEmp = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(590, 388));

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmpleados.setToolTipText("");
        tblEmpleados.setDragEnabled(true);
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        javax.swing.GroupLayout pnlEmpleadosTablaLayout = new javax.swing.GroupLayout(pnlEmpleadosTabla);
        pnlEmpleadosTabla.setLayout(pnlEmpleadosTablaLayout);
        pnlEmpleadosTablaLayout.setHorizontalGroup(
            pnlEmpleadosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpleadosTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlEmpleadosTablaLayout.setVerticalGroup(
            pnlEmpleadosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpleadosTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel1.setText("Nombre");

        txtNombreEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpActionPerformed(evt);
            }
        });

        jLabel3.setText("Sucursal");

        cmbSucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Empleado");

        btnCrear.setText("Nuevo");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtCedulaEmp))
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cmbSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cmbSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtCedulaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnCrear))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEmpleadosTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEmpleadosTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        limpiarTabla();
        String comando = "";
        String numerosucur = cmbSucursales.getItemAt(cmbSucursales.getSelectedIndex());
        String cedula = txtCedulaEmp.getText().trim();
        String nombre = txtNombreEmp.getText().trim();
        if (txtCedulaEmp.getText().trim().isEmpty() && txtNombreEmp.getText().trim().isEmpty()) {
            if (numerosucur.isBlank()) {
                comando = "SELECT * FROM empleado";
            } else {
                comando = "SELECT * FROM empleado "
                        + "JOIN trabaja ON empleado.idempleado = trabaja.idempleado "
                        + "WHERE trabaja.numerosucur = " + numerosucur;
            }

        } else {
            // Construimos la consulta basada en las condiciones
            StringBuilder sb = new StringBuilder("SELECT * FROM empleado ");
            boolean hasJoin = false;

            if (!numerosucur.isBlank()) {
                sb.append("JOIN trabaja ON empleado.idempleado = trabaja.idempleado ");
                hasJoin = true;
            }

            sb.append("WHERE ");

            if (!cedula.isEmpty()) {
                sb.append("empleado.idempleado = '").append(cedula).append("' ");
                if (!nombre.isEmpty() || !numerosucur.isBlank()) {
                    sb.append("AND ");
                }
            }

            if (!nombre.isEmpty()) {
                sb.append("empleado.nombre LIKE '%").append(nombre).append("%' ");
                if (!numerosucur.isBlank()) {
                    sb.append("AND ");
                }
            }

            if (!numerosucur.isBlank()) {
                sb.append("trabaja.numerosucur = '").append(numerosucur).append("' ");
            }

            comando = sb.toString();
        }
        System.out.println(comando);
        LlenarTabla(comando);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        JPanel pnlEditar = new PnlEditarEmpleado();
        String numerosucur = cmbSucursales.getItemAt(cmbSucursales.getSelectedIndex());

        estado = false;
        System.out.println(numerosucur);

        int maxID = 0;
        for (String id : PnlEmpleados.idEmpleado) {
            int num = Integer.parseInt(id.substring(1));
            if (num > maxID) {
                maxID = num;
            }
        }
        System.out.println(maxID);
        System.out.println(PnlEmpleados.estado);
        int nuevoNum = maxID + 1;
        String pkID = String.format("E%04d", nuevoNum);
        PnlEditarEmpleado.txtIDEmp.setText(pkID);
        PnlEditarEmpleado.txtIDEmp.setEditable(false);
        agregarPanel(pnlEditar);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        int index = tblEmpleados.getSelectedRow();

        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila", "Acceso no permitido", 2);
        } else {
            try {
                registro = (Vector) dtm.getDataVector().elementAt(index);
                System.out.println(registro.elementAt(0).toString());
                JPanel pnlEditar = new PnlEditarEmpleado();
                String comando = "SELECT * FROM empleado WHERE idempleado = '" + registro.elementAt(0).toString() + "'";
                PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
                ResultSet rs = pst.executeQuery();
                PnlEditarEmpleado.txtIDEmp.setEditable(false);
                while (rs.next()) {
                    PnlEditarEmpleado.txtIDEmp.setText(rs.getString(1));
                    PnlEditarEmpleado.txtNombre.setText(rs.getString(2));
                    PnlEditarEmpleado.txtCedula.setText(rs.getString(3));
                    PnlEditarEmpleado.txtTelefono.setText(rs.getString(4));
                    PnlEditarEmpleado.txtDireccion.setText(rs.getString(5));
                }
                agregarPanel(pnlEditar);
                pst.execute();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        try {
            // TODO add your handling code here:
            int index = tblEmpleados.getSelectedRow();
            String cmd = "DELETE FROM trabaja WHERE idempleado = ?";
            PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(cmd);
            registro = (Vector) dtm.getDataVector().elementAt(index);

            pst.setString(1, registro.elementAt(0).toString());
            String comando = "DELETE FROM empleado WHERE idempleado = ?";
            PreparedStatement pst2 = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
            pst2.setString(1, registro.elementAt(0).toString());
            pst.executeUpdate();
            pst2.executeUpdate();
            JOptionPane.showMessageDialog(null, "Empleado eliminado exitosamente", "Transacción exitosa",
                    JOptionPane.INFORMATION_MESSAGE);
            limpiarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(PnlEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        LlenarTabla("SELECT * FROM empleado");
        System.out.println("Finalizado");
    }//GEN-LAST:event_btnEliminarActionPerformed
    public static void agregarPanel(JPanel pnl) {
        //ajustamos el tamaño
        pnl.setSize(578, 266);
        //colocamos, la esquina superior izquierda posee coordenadas (0,0)
        pnl.setLocation(0, 0);
        //remueve lo del panel inicio
        pnlEmpleadosTabla.removeAll();
        //en el panel inicio agregue el panel clientes con una ubicación
        pnlEmpleadosTabla.add(pnl, BorderLayout.CENTER);
        //elimina toda la jerarquia y la construye nuevamente
        pnlEmpleadosTabla.revalidate();
        pnlEmpleadosTabla.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    public static javax.swing.JComboBox<String> cmbSucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel pnlEmpleadosTabla;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtCedulaEmp;
    private javax.swing.JTextField txtNombreEmp;
    // End of variables declaration//GEN-END:variables
}
