/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Conexion;
import static Vista.pnlClientes.registro;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mauri
 */
public class PnlEditarCliente extends javax.swing.JPanel {

    /**
     * Creates new form PnlEditarSucursales
     */
    public PnlEditarCliente() {
        initComponents();
        System.out.println(pnlSucursales.estado + " estado");
        PnlEmpleados.llenarCmb(cmbSucursales);
        seleccionarCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        btgCiudad = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlSucursalEd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbSucursales = new javax.swing.JComboBox<>();
        rbtQuito = new javax.swing.JRadioButton();
        rbtGuayaquil = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(578, 264));

        pnlSucursalEd.setBackground(new java.awt.Color(255, 255, 255));
        pnlSucursalEd.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        jLabel1.setText("ID");

        jLabel2.setText("Sucursal");

        jLabel3.setText("Ciudad");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cmbSucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btgCiudad.add(rbtQuito);
        rbtQuito.setText("Norte");

        btgCiudad.add(rbtGuayaquil);
        rbtGuayaquil.setText("Sur");
        rbtGuayaquil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGuayaquilActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("CI");

        javax.swing.GroupLayout pnlSucursalEdLayout = new javax.swing.GroupLayout(pnlSucursalEd);
        pnlSucursalEd.setLayout(pnlSucursalEdLayout);
        pnlSucursalEdLayout.setHorizontalGroup(
            pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(rbtQuito)
                                .addGap(18, 18, 18)
                                .addComponent(rbtGuayaquil))
                            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre))))
                    .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSucursalEdLayout.createSequentialGroup()
                            .addGap(176, 176, 176)
                            .addComponent(btnGuardar)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelar))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        pnlSucursalEdLayout.setVerticalGroup(
            pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtQuito)
                    .addComponent(rbtGuayaquil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSucursalEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSucursalEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        JPanel pnlTabla = new pnlClientes();
        Inicio.agregarPanelDerecho(pnlTabla);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (pnlClientes.estado) {
            try {
                String numeroSucu = cmbSucursales.getSelectedItem().toString();
                String ciudad = "";
                String nombre = txtNombre.getText().toUpperCase();
                String cedula = txtCedula.getText();
                if (rbtGuayaquil.isSelected()) {
                    ciudad = "SUR";
                } else {
                    ciudad = "NORTE";
                }
                String comando = "UPDATE cliente SET "
                        + "numerosucur = ?, "
                        + "nombrecliente = ?, "
                        + "ciudadcliente = ?, "
                        + "cicliente = ? "
                        + "WHERE codigocliente = ?";
                PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);

                pst.setString(1, numeroSucu);
                pst.setString(2, nombre);
                pst.setString(3, ciudad);
                pst.setString(4, cedula);
                pst.setString(5, txtID.getText());

                System.out.println(pst.executeUpdate() + " " + txtID.getText().trim());
                System.out.println("Terminado");
                JOptionPane.showMessageDialog(null, "Cliente actualizado exitosamente", "Transacción exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
                JPanel pnlTabla = new pnlClientes();
                Inicio.agregarPanelDerecho(pnlTabla);
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            try {
                String numeroSucu = cmbSucursales.getSelectedItem().toString();
                String ciudad = "";
                String nombre = txtNombre.getText().toUpperCase();
                String cedula = txtCedula.getText();
                String ID = txtID.getText().toUpperCase();
                System.out.println("sucursal: " + numeroSucu);
                if (rbtGuayaquil.isSelected()) {
                    ciudad = "SUR";
                } else {
                    ciudad = "NORTE";
                }
                String comando = "";
                
                if (pnlInicioSesion.usuario.equals("roberth")) {
                    comando = "INSERT INTO cliente_norte (codigocliente, numerosucur, nombrecliente, ciudadcliente, fechanac_cliente,cicliente) "
                            + "VALUES (?,?,?,?, CURRENT_DATE,?)";
                } else {
                    comando = "INSERT INTO cliente_sur (codigocliente, numerosucur, nombrecliente, ciudadcliente, fechanac_cliente,cicliente) "
                            + "VALUES (?,?,?,?, CURRENT_DATE,?)";
                }

                PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);

                pst.setString(1, ID);
                pst.setString(2, numeroSucu);
                pst.setString(3, nombre);
                pst.setString(4, ciudad);
                pst.setString(5, cedula);

                System.out.println(pst.executeUpdate());
                System.out.println("Terminado");
                JOptionPane.showMessageDialog(null, "Cliente insertado exitosamente", "Transacción exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
                JPanel pnlTabla = new pnlClientes();
                Inicio.agregarPanelDerecho(pnlTabla);
            } catch (SQLException ex) {
                Logger.getLogger(PnlEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbtGuayaquilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGuayaquilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtGuayaquilActionPerformed
    private void seleccionarCmb() {
        try {
            String comando = "";
            if (pnlInicioSesion.usuario.equals("roberth")) {
                comando = "SELECT s.numerosucur FROM cliente_norte c JOIN "
                        + " sucursal s on c.numerosucur = s.numerosucur "
                        + "WHERE c.codigocliente = '" + registro.elementAt(0).toString() + "'";
            } else {
                comando = "SELECT s.numerosucur FROM cliente_sur c JOIN "
                        + " sucursal s on c.numerosucur = s.numerosucur "
                        + "WHERE c.codigocliente = '" + registro.elementAt(0).toString() + "'";
            }

            PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
            ResultSet rs = pst.executeQuery();
            String valor = "";
            while (rs.next()) {
                valor = rs.getString(1);
            }
            System.out.println(valor + " valor " + registro.elementAt(0).toString());
            cmbSucursales.setSelectedItem(valor);
            System.out.println(valor);
        } catch (Exception ex) {
            Logger.getLogger(PnlEditarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            cmbSucursales.setSelectedIndex(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCiudad;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> cmbSucursales;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlSucursalEd;
    public static javax.swing.JRadioButton rbtGuayaquil;
    public static javax.swing.JRadioButton rbtQuito;
    public static javax.swing.JTextField txtCedula;
    public static javax.swing.JTextField txtID;
    public static javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
