/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Conexion;
import static Vista.pnlTarjetas.registro;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mauri
 */
public class PnlEditarTarjeta extends javax.swing.JPanel {

    /**
     * Creates new form PnlEditarSucursales
     */
    public PnlEditarTarjeta() {
        initComponents();
        llenarCmb(cmbClientes);
    }

    static public void llenarCmb(JComboBox cmb) {
        try {
            cmb.removeAllItems();
            String comando = "SELECT codigocliente FROM cliente";
            PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String sucursalID = rs.getString(1);
                cmb.addItem(sucursalID);
            }
            pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void seleccionarCmb() {
        try {
            String comando = "SELECT codigocliente FROM tarjeta WHERE numerotarjeta = " + registro.elementAt(0).toString() + "";
            PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
            ResultSet rs = pst.executeQuery();
            String valor = "";
            while (rs.next()) {
                valor = rs.getString(1);
            }
            cmbClientes.setSelectedItem(valor);
            System.out.println(valor);
        } catch (Exception ex) {
            Logger.getLogger(PnlEditarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            cmbClientes.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        btgCiudad = new javax.swing.ButtonGroup();
        pnlSucursalEd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbtVisa = new javax.swing.JRadioButton();
        rbtMC = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbClientes = new javax.swing.JComboBox<>();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(578, 264));

        pnlSucursalEd.setBackground(new java.awt.Color(255, 255, 255));
        pnlSucursalEd.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarjeta"));

        jLabel1.setText("Numero");

        jLabel2.setText("Codigo");

        jLabel3.setText("Tipo");

        btgCiudad.add(rbtVisa);
        rbtVisa.setText("VISA");
        rbtVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtVisaActionPerformed(evt);
            }
        });

        btgCiudad.add(rbtMC);
        rbtMC.setText("MASTERCARD");
        rbtMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMCActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliente");

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlSucursalEdLayout = new javax.swing.GroupLayout(pnlSucursalEd);
        pnlSucursalEd.setLayout(pnlSucursalEdLayout);
        pnlSucursalEdLayout.setHorizontalGroup(
            pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                        .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(txtCodigo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSucursalEdLayout.createSequentialGroup()
                        .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                                .addComponent(rbtVisa)
                                .addGap(25, 25, 25)
                                .addComponent(rbtMC))
                            .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        pnlSucursalEdLayout.setVerticalGroup(
            pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtVisa)
                    .addComponent(rbtMC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSucursalEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSucursalEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        JPanel pnlSucursal = new pnlTarjetas();
        Inicio.agregarPanelDerecho(pnlSucursal);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (pnlTarjetas.estado) {
            System.out.println("editar " + pnlSucursales.estado);
            try {
                String numero = txtNumero.getText().trim();
                String codigo = txtCodigo.getText();
                String tipo = "";
                if (rbtMC.isSelected()) {
                    tipo = "MASTERCARD";
                } else {
                    tipo = "VISA";
                }
                String cliente = cmbClientes.getSelectedItem().toString();
                String comando = "UPDATE tarjeta SET codigocliente = ? where numerotarjeta = ?";
                PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
                pst.setString(1, cliente);
                pst.setString(2, numero);
                System.out.println(pst.executeUpdate());
                JOptionPane.showMessageDialog(null, "Tarjeta actualizada exitosamente", "Transacción exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
                JPanel pnlTabla = new pnlTarjetas();
                Inicio.agregarPanelDerecho(pnlTabla);
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            try {
                String numero = txtNumero.getText();
                String codigo = txtCodigo.getText();
                String tipo = "";
                if (rbtMC.isSelected()) {
                    tipo = "MASTERCARD";
                } else {
                    tipo = "VISA";
                }
                String cliente = cmbClientes.getSelectedItem().toString();
                String comando = "INSERT INTO tarjeta (numerotarjeta, codigocliente, nombretarjeta, codigotarjeta, fechavenctarjeta) "
                        + "VALUES ("+numero+",'"+cliente+ "','"+tipo+"','"+codigo+"',CURRENT_DATE)";
                PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
                System.out.println(pst.executeUpdate() + " "+ comando);
                JOptionPane.showMessageDialog(null, "Tarjeta agregada exitosamente", "Transacción exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
                JPanel pnlTabla = new pnlTarjetas();
                Inicio.agregarPanelDerecho(pnlTabla);
            } catch (SQLException ex) {
                Logger.getLogger(PnlEditarTarjeta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbtMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtMCActionPerformed

    private void rbtVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtVisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtVisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCiudad;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    public static javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlSucursalEd;
    public static javax.swing.JRadioButton rbtMC;
    public static javax.swing.JRadioButton rbtVisa;
    public static javax.swing.JTextField txtCodigo;
    public static javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
