/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.sql.PreparedStatement;
import javax.swing.JPanel;

/**
 *
 * @author mauri
 */
public class PnlEditarSucursales extends javax.swing.JPanel {

    /**
     * Creates new form PnlEditarSucursales
     */
    public PnlEditarSucursales() {
        initComponents();
        System.out.println(pnlSucursales.estado + " estado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        btgCiudad = new javax.swing.ButtonGroup();
        pnlSucursalEd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroSuc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbtQuito = new javax.swing.JRadioButton();
        rbtGuayaquil = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(578, 264));

        pnlSucursalEd.setBackground(new java.awt.Color(255, 255, 255));
        pnlSucursalEd.setBorder(javax.swing.BorderFactory.createTitledBorder("Sucursal"));

        jLabel1.setText("Numero");

        jLabel2.setText("Direccion");

        jLabel3.setText("Ciudad");

        btgCiudad.add(rbtQuito);
        rbtQuito.setText("Quito");

        btgCiudad.add(rbtGuayaquil);
        rbtGuayaquil.setText("Guayaquil");
        rbtGuayaquil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGuayaquilActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSucursalEdLayout = new javax.swing.GroupLayout(pnlSucursalEd);
        pnlSucursalEd.setLayout(pnlSucursalEdLayout);
        pnlSucursalEdLayout.setHorizontalGroup(
            pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(rbtQuito)
                        .addGap(18, 18, 18)
                        .addComponent(rbtGuayaquil))
                    .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                        .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumeroSuc, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(txtDireccion))))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        pnlSucursalEdLayout.setVerticalGroup(
            pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSucursalEdLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroSuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtQuito)
                    .addComponent(rbtGuayaquil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(pnlSucursalEdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSucursalEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSucursalEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        JPanel pnlSucursal = new pnlSucursales();
        Inicio.agregarPanelDerecho(pnlSucursal);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (pnlSucursales.estado) {
            System.out.println("editar "+pnlSucursales.estado);
            try {
                String numeroSucu = txtNumeroSuc.getText().trim();
                String direccion = txtDireccion.getText();
                String ciudad = "";
                if (rbtGuayaquil.isSelected()) {
                    ciudad = "GUAYAQUIL";
                } else {
                    ciudad = "QUITO";
                }
                String comando = " ";
                PreparedStatement pst = pnlInicioSesion.conn.getConnSin().prepareStatement(comando);
                if(!numeroSucu.isBlank() && !direccion.isBlank() ){
                    pst.setString(1, numeroSucu);
                }
                
            } catch (Exception e) {
                System.out.println(e);
            }
        }else{
            
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbtGuayaquilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGuayaquilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtGuayaquilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCiudad;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlSucursalEd;
    public static javax.swing.JRadioButton rbtGuayaquil;
    public static javax.swing.JRadioButton rbtQuito;
    public static javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtNumeroSuc;
    // End of variables declaration//GEN-END:variables
}
